version: "3.8"

services:
  sito-web:
    build: .
    container_name: informaticasi-web
    ports:
      - "8080:80" # Mappa la porta 8080 del tuo computer alla porta 80 del container
    volumes:
      - ./src:/var/www/html # Sincronizza i file in tempo reale per lo sviluppo
    restart: unless-stopped
  